#!/bin/bash

#SBATCH -n 8                              # Number of cores
#SBATCH --time=48:00:00                    # hours:minutes:seconds
#SBATCH --mem-per-cpu=32000
#SBATCH --tmp=10                         # per node!!
#SBATCH --gpus=rtx_2080_ti:1              # Ohter options are: --gpus=gtx_1080_ti:1  --gpus=rtx_2080_ti:1
#SBATCH --job-name=train_job
#SBATCH --output=./jobs/train_dialogpt.out
#SBATCH --error=./jobs/train_dialogpt.err

source /cluster/home/daizhang/venvs/csnlp_venv/bin/activate
module load gcc/8.2.0 python_gpu/3.8.5 eth_proxy
python train_dialogpt.py
