#!/bin/bash

#SBATCH -n 8                              # Number of cores
#SBATCH --time=16:00:00                    # hours:minutes:seconds
#SBATCH --mem-per-cpu=16000
#SBATCH --tmp=4000                         # per node!!
#SBATCH --gpus=rtx_2080_ti:1              # Ohter options are: --gpus=gtx_1080_ti:1  --gpus=rtx_2080_ti:1
#SBATCH --job-name=train_job
#SBATCH --output=./jobs/train.out
#SBATCH --error=./jobs/train.err

source /cluster/scratch/yaqqin/venvs/csnlp_venv/bin/activate
module load gcc/8.2.0 python_gpu/3.8.5 eth_proxy
python train.py --num_steps 4